# Azure Pipelines: build the Webclient

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  inputs:
    command: 'install'
  displayName: NPM install

- task: Grunt@0
  inputs:
    gruntFile: 'Gruntfile.js'
    targets: 'dist-all'
  displayName: Build distribution directory with Grunt

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(build.sourcesDirectory)/dist'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(build.artifactStagingDirectory)'
    publishLocation: 'pipeline'
    artifactName: wwt-webclient-deployment
  displayName: Publish web deployment artifacts
